---
- hosts: abr
  become: True
  become_user: root
  tasks:
    - name: download php-fpm exporter
      get_url:
        url: https://github.com/hipages/php-fpm_exporter/releases/download/v1.2.1/php-fpm_exporter_1.2.1_linux_amd64
        dest: /tmp
    - name: move node exporter to /usr/local/bin
      copy:
        src: /tmp/php-fpm_exporter_1.2.1_linux_amd64
        dest: /usr/local/bin/
        remote_src: yes
        owner: root
        group: root
        mode: 0755
    - name: install unit file to systemd
      template:
        src: templates/php-fpm_exporter.j2
        dest: /etc/systemd/system/php-fpm_exporter.service
        owner: root
        group: root
        mode: 0600
    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: php-fpm_exporter.service
